/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Avataaars = {
  radius?: number;
  r?: number;
  width?: number;
  w?: number;
  height?: number;
  h?: number;
  margin?: number;
  m?: number;
  background?: string | "transparent";
  b?: string | "transparent";
  [k: string]: unknown;
} & {
  style?: "transparent" | "circle";
  mode?: "include" | "exclude";
  top?: ("longHair" | "shortHair" | "eyepatch" | "hat" | "hijab" | "turban")[];
  topChance?: Chance;
  hatColor?: Color;
  hairColor?: HairColor;
  accessories?: ("kurt" | "prescription01" | "prescription02" | "round" | "sunglasses" | "wayfarers")[];
  accessoriesChance?: Chance;
  accessoriesColor?: Color;
  facialHair?: ("medium" | "light" | "majestic" | "fancy" | "magnum" | "pastel" | "gray")[];
  facialHairChance?: Chance;
  facialHairColor?: HairColor;
  clothes?: string;
  clothesColor?: Color;
  eyes?: (
    | "close"
    | "cry"
    | "default"
    | "dizzy"
    | "roll"
    | "happy"
    | "hearts"
    | "side"
    | "squint"
    | "surprised"
    | "wink"
    | "winkWacky"
  )[];
  eyebrow?: ("angry" | "default" | "flat" | "raised" | "sad" | "unibrow" | "up" | "frown")[];
  mouth?: (
    | "concerned"
    | "default"
    | "disbelief"
    | "eating"
    | "grimace"
    | "sad"
    | "scream"
    | "serious"
    | "smile"
    | "tongue"
    | "twinkle"
    | "vomit"
  )[];
  skin?: ("tanned" | "yellow" | "pale" | "light" | "brown" | "darkBrown" | "black")[];
  [k: string]: unknown;
};
export type Chance = number;
export type Color = ("black" | "blue" | "gray" | "heather" | "pastel" | "pink" | "red" | "white")[];
export type HairColor = ("auburn" | "black" | "blonde" | "brown" | "pastel" | "platinum" | "red" | "gray")[];
